<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=Edge" />
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
	<meta name="apple-mobile-web-app-capable" content="yes">
	<meta name="apple-mobile-web-app-status-bar-style" content="black">
	<meta name="apple-touch-fullscreen" content="yes">
	<meta name="format-detection" content="telephone=no, email=no">
	<title>保险岛钻石服务公告</title>
	<style>
		*{
			margin: 0;
			padding: 0;
		}
    body{
      background: #f5f5f5;
    }
    i{
      font-style:normal
    }
		.clent-logo img{
			width: 100%;
      max-width: 900px;
      margin:0 auto;
      display: block;
		}
    .notice-wrap{
      width:90%;
      background-color: #fff;
      max-width: 800px;
      height: 500px;
      margin: 0 auto;
      
    }
    .notice-wrap h6{
      font-size: 18px;
      color: #1bbe60;
      font-weight:bold;
      text-align: center;
      line-height: 50px;
      
    }
    .notice-wrap section{
      padding: 16px;
      background-color: #fff;
      margin-bottom: 20px;
    }
    .notice-wrap p{
      font-size: 12px;
      line-height: 20px;
      text-indent: 2em;
      margin-bottom: 10px;
    }
    .line{
      height: 34px;
      border-bottom: 1px dotted #efefef;
      width: 100%;
    }
    .ecode{
      width: 160px;
      display: block;
      margin:0 auto;
      margin-top:15px;
    }
    .ecode img{
      width: 100%;
      display: block;
    }
    @media screen and (min-width: 400px) {
      .notice-wrap p{
        font-size: 14px;
      }
      .notice-wrap h6{
        font-size: 22px;
      }
}
	</style>
</head>
<body>
  <a class="clent-logo" href="//www.bxd365.com/"><img src="//s29.9956.cn/res/bxd365/images/gg_logo.png" alt="保险岛"></a>
  <div class="notice-wrap">
    <section>
      <h6>声明</h6>
   <p>近日，我司（郑州易保网络科技有限公司）接到部分合作客户反馈：有福建等地号段的固定电话及手机号码与其联系，谎称我司旗下平台“保险岛”认证客服，对其进行电话诈骗并实施侮辱、诽谤行为，该行为已经严重危害我司及相关客户的合法权益，并涉嫌违法犯罪。为保护客户利益，维护我司形象，现郑重声明如下：</p>
   <p>一、“保险岛”是郑州易保网络科技有限公司旗下平台，郑州易保网络科技有限公司享有其商标使用权及平台运营权，“保险岛”认证客服均经“保险岛”官方认证、授权。如果对以“保险岛”名义与您接洽的人员身份存有疑虑，请及时登录“保险岛”认证客服验证专属页面：https://www.bxd365.com/yanzheng或拨打“保险岛”全国唯一指定官方热线：4008885365确认该人员的真实身份！</p>
   <p>二、对任何冒用、假借我司名义进行违法活动的网站、机构及个人，我司已经向主管公安机关及网络监察部门举报；并强烈谴责擅自使用我司企业名称，假冒我司商号、商标标识，发布虚假及侵权信息，损害我司名誉，欺骗用户之违法行为，我司已经全权委托律师依照法律程序依法维护我司正当权益。</p>
   <p>三、敬告所有欺诈、侮辱、诽谤行为的实施者，请立即删除所有侵权内容，停止一切侵害行为。同时欢迎广大客户通过“保险岛”官方投诉邮箱：tousu@bxd365.com及“保险岛”微信公众号“bxd365”向我司提供有关不法分子冒充“保险岛”进行骚扰、诈骗的线索、证据（包括但不限于诈骗电话录音、聊天记录等内容）。</p>
   <p>四、我司对非本司认证客服人员的任何机构、个人从事的所有商业活动均不承担任何法律责任，敬请广大客户提高警惕，谨防上当，避免受骗。对于近期他人冒充我司进行商业活动，给广大客户带来的不便，十分抱歉。</p>
   <p style="text-indent:0;">特此声明！</p>
   <p></p>
   <p style="text-align:right">郑州易保网络科技有限公司</p>
   <p style="text-align:right">2018年12月3日</p>
   <div class="line"></div>
   <div style="margin-top:34px"></div>
   <p style="text-indent:0;">● 保险岛微信公众号，保险行业新媒体平台前驱，百万代理人的不二选择！ </p>
   <p style="text-indent:0;">● 这里有最新的行业动态解读，有料的保险干货，更专业的展业获客工具，一个微信带你玩转朋友圈！</p>
   <p style="text-indent:0;">● 微信扫描公众号关注官方微信，新用户回复 “陌拜” 即可获得陌拜秘籍一份 ，帮你打通展业获客通道</p>
   <div class="ecode"><img src="//s29.9956.cn/res/bxd365/images/notice-ecode.jpg"></div>
  </section>
  </div>
</body>
</html>